before:
  hooks:
    - go get -v -d ./...
builds:
  - id: "vault-util"
    binary: vault-util
    main: main.go
    ldflags:
      - -s -w -X github.com/chef/vault-util/commands.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64