before:
  hooks:
    - go get -v -d ./...
builds:
  - id: "vault-util"
    binary: vault-util
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64